name: ny_taxi_rides
version: '1.0'
config-version: 2

profile: ny_taxi_rides

source-paths: ["models"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ny_taxi_rides:
    staging:
      +materialized: view
    marts:
      +materialized: table
name: ny_taxi_rides

profile: ny_taxi_rides

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  ny_taxi_rides:
    +schema: raw

models:
  ny_taxi_rides:
    +static_analysis: strict
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    marts:
      +materialized: table
